/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasHeader: typeof import('./src/components/header/CanvasHeader.vue')['default']
    HeaderCenter: typeof import('./src/components/header/HeaderCenter.vue')['default']
    HeaderLeft: typeof import('./src/components/header/HeaderLeft.vue')['default']
    HeaderRight: typeof import('./src/components/header/HeaderRight.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NPopover: typeof import('naive-ui')['NPopover']
  }
}
