/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasHeader: typeof import('./src/components/header/CanvasHeader.vue')['default']
    ElementAttributes: typeof import('./src/components/ElementAttributes.vue')['default']
    ElementPalette: typeof import('./src/components/ElementPalette.vue')['default']
    HeaderCenter: typeof import('./src/components/header/HeaderCenter.vue')['default']
    HeaderLeft: typeof import('./src/components/header/HeaderLeft.vue')['default']
    HeaderRight: typeof import('./src/components/header/HeaderRight.vue')['default']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NPopover: typeof import('naive-ui')['NPopover']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
  }
}
